FROM ubuntu:20.04

ENV LANG C.UTF-8
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update \
  && apt-get -y install \
    sudo \
    curl \
    wget \
    faad \
    flac \
    lame \
    sox \
    libio-socket-ssl-perl \
    libpython2.7 \
    libfreetype6 \
    libfont-freetype-perl \
    libcrypt-openssl-rsa-perl \
    libio-socket-inet6-perl \
    libwww-perl \
    libcrypt-openssl-bignum-perl \
    libcrypt-openssl-random-perl \
    libcrypt-ssleay-perl \
    avahi-utils \
    ffmpeg \
    libinline-python-perl \
    libnet-ssleay-perl \
    opus-tools \
    build-essential \
    libssl-dev \
    libffi-dev \
    libxml2-dev \
    libxslt1-dev \
    python3-dev \
    python3-pip
